
name: publish
on: workflow_dispatch
jobs:
  build_windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'

      - run: flutter config --enable-windows-desktop
      - run: flutter build windows

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - run: flutter config --enable-linux-desktop
      - run: flutter build linux

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos

  build_android:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'

      - run: flutter pub get
      - run: flutter build apk

  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign