
name: build_and_publish
on: workflow_dispatch
jobs:
  build_windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'

      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows/runner/Release

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: build/linux/x64/release/bundle


  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - uses: actions/upload-artifact@v3
        with:
          name: macos
          path: build/macos/Build/Products/Release

  build_android:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'

      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: android
          path: build/app/outputs/flutter-apk.apk

  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: |
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - uses: actions/upload-artifact@v3
        with:
          name: ios
          path: build/ios/iphoneos/app.ipa

#  publish:
#    runs-on: ubuntu-latest
#    needs: [build_windows, build_linux, build_macos, build_android, build_ios]
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: thedoctor0/zip-release@master
#        with:
#          type: "zip"
#          filename: "windows.zip"
#          path: "./build/windows/runner/Release"
#
#      - uses: thedoctor0/zip-release@master
#        with:
#          type: "zip"
#          filename: "linux.zip"
#          path: "./build/linux/x64/release/bundle"
#
#      - uses: thedoctor0/zip-release@master
#        with:
#          type: "zip"
#          filename: "macos.zip"
#          path: "./build/macos/Build/Products/Release"
#
#      - uses: ncipollo/release-action@v1
#        with:
#          artifacts: "windows.zip,linux.zip,macos.zip,build/app/outputs/flutter-apk.apk,build/ios/iphoneos/app.ipa"
#          name: 1.0
#          tag: 1.0
#          token: ${{ secrets.GITHUB_TOKEN }}